# Generated by Django 5.2.5 on 2026-05-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='permis_conduire',
            new_name='photo_permis',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='carte_grise',
        ),
        migrations.AddField(
            model_name='customuser',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='assurance_vehicule',
            field=models.FileField(blank=True, null=True, upload_to='documents/assurance/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='capacite_chargement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='carte_transporteur',
            field=models.FileField(blank=True, null=True, upload_to='documents/carte_transporteur/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='corridors_couverts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='document_ifu',
            field=models.FileField(blank=True, null=True, upload_to='documents/ifu/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nom_responsable',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nom_societe',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nombre_camions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='numero_immatriculation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='numero_permis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo_identite',
            field=models.FileField(blank=True, null=True, upload_to='documents/identite/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo_vehicule',
            field=models.FileField(blank=True, null=True, upload_to='documents/vehicules/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='quartier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='type_camion_principal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='type_vehicule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
