# Generated by Django 5.2.5 on 2026-06-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('type_profil', models.CharField(choices=[('client', 'Client / Voyageur'), ('hotelier', 'Hôtelier / Gestionnaire'), ('partenaire', 'Partenaire commercial'), ('autre', 'Autre')], max_length=20)),
                ('sujet', models.CharField(choices=[('reservation', 'Problème de réservation'), ('paiement', 'Question de paiement'), ('technique', 'Problème technique'), ('partenariat', 'Partenariat'), ('autre', 'Autre')], max_length=20)),
                ('urgence', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('critique', 'Critique')], default='normal', max_length=20)),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
