# Generated by Django 5.2.5 on 2026-06-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_message_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagecontact',
            name='sujet',
            field=models.CharField(choices=[('reservation', 'Problème de réservation'), ('paiement', 'Question de paiement'), ('compte', 'Mon compte / connexion'), ('hotel', "Signalement d'un hôtel"), ('technique', 'Problème technique'), ('partenariat', 'Partenariat'), ('autre', 'Autre')], max_length=20),
        ),
    ]
