# Generated by Django 6.0.6 on 2026-06-06 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_abonnement', models.CharField(choices=[('freemium', 'Freemium (3%)'), ('pro', 'Pro (1.5%)')], max_length=20)),
                ('taux_commission', models.DecimalField(decimal_places=4, max_digits=5)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré'), ('annule', 'Annulé')], default='actif', max_length=20)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference_paiement', models.CharField(blank=True, max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_brut', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taux', models.DecimalField(decimal_places=4, max_digits=5)),
                ('montant_commission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_hotel', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('calcule', 'Calculé'), ('verse', "Versé à l'hôtel"), ('litige', 'En litige')], default='calcule', max_length=20)),
                ('date_calcul', models.DateTimeField(auto_now_add=True)),
                ('date_versement', models.DateTimeField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='hotels.hotel')),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='reservations.paiement')),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
                'ordering': ['-date_calcul'],
            },
        ),
    ]
