# Generated by Django 5.2.5 on 2026-06-08 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
        ('hotels', '0006_alter_hotel_type_abonnement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='type_abonnement',
            field=models.CharField(choices=[('freemium', 'Freemium (3%)'), ('pro', 'Pro (5%)')], max_length=20),
        ),
        migrations.CreateModel(
            name='DemandeUpgradePro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvée'), ('rejete', 'Rejetée')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('message_admin', models.TextField(blank=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_upgrade', to='hotels.hotel')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande upgrade Pro',
                'verbose_name_plural': 'Demandes upgrade Pro',
                'ordering': ['-date_demande'],
            },
        ),
    ]
