# Generated by Django 5.2.5 on 2026-06-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_retrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrait',
            name='methode',
            field=models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('moov', 'Moov Money'), ('carte', 'Carte bancaire')], max_length=10),
        ),
    ]
