# Generated by Django 6.0.6 on 2026-06-06 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenementNational',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('categorie', models.CharField(choices=[('culturel', 'Culturel'), ('religieux', 'Religieux'), ('national', 'Fête nationale'), ('sportif', 'Sportif'), ('autre', 'Autre')], default='culturel', max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('region', models.CharField(blank=True, max_length=100)),
                ('villes_concernees', models.JSONField(blank=True, default=list)),
                ('est_actif', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='evenements/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Événement National',
                'verbose_name_plural': 'Événements Nationaux',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='MiseEnAvantHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_boost', models.PositiveSmallIntegerField(default=0)),
                ('date_boost_debut', models.DateField()),
                ('date_boost_fin', models.DateField()),
                ('est_actif', models.BooleanField(default=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mises_en_avant', to='evenements.evenementnational')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mises_en_avant', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Mise en avant',
                'unique_together': {('evenement', 'hotel')},
            },
        ),
    ]
