# Generated by Django 6.0.6 on 2026-07-10 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('icone', models.CharField(blank=True, max_length=50)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie de service',
                'verbose_name_plural': 'Catégories de service',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProximite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('horaires', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('osm', 'OpenStreetMap'), ('manuel', 'Manuel')], default='manuel', max_length=10)),
                ('identifiant_externe', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='assistance.categorieservice')),
            ],
            options={
                'verbose_name': 'Service de proximité',
                'verbose_name_plural': 'Services de proximité',
                'ordering': ['ville', 'nom'],
            },
        ),
    ]
