# Generated by Django 6.0.6 on 2026-07-10 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproximite',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='assistance.categorieservice'),
        ),
        migrations.AlterField(
            model_name='serviceproximite',
            name='identifiant_externe',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
