# Generated by Django 5.2.5 on 2026-05-10 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demandes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant en FCFA', max_digits=12)),
                ('operateur', models.CharField(choices=[('mtn', 'MTN MoMo'), ('moov', 'Moov Money')], max_length=10)),
                ('numero_telephone', models.CharField(help_text='Numéro Mobile Money du commerçant', max_length=20)),
                ('reference_transaction', models.CharField(blank=True, help_text='Référence de la transaction Mobile Money', max_length=100, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('bloque', 'Bloqué (Escrow)'), ('libere', 'Libéré'), ('rembourse', 'Remboursé'), ('echoue', 'Échoué')], default='en_attente', max_length=20)),
                ('motif_remboursement', models.TextField(blank=True, help_text='Motif du remboursement en cas de litige', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_blocage', models.DateTimeField(blank=True, null=True)),
                ('date_liberation', models.DateTimeField(blank=True, null=True)),
                ('date_remboursement', models.DateTimeField(blank=True, null=True)),
                ('commercant', models.ForeignKey(limit_choices_to={'role': 'commercant'}, on_delete=django.db.models.deletion.CASCADE, related_name='paiements_effectues', to=settings.AUTH_USER_MODEL)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='demandes.demande')),
                ('transporteur', models.ForeignKey(limit_choices_to={'role__in': ['transporteur', 'societe']}, on_delete=django.db.models.deletion.CASCADE, related_name='paiements_recus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_creation'],
            },
        ),
    ]
