# Generated by Django 5.2.5 on 2026-06-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de paiement'), ('payee', 'Payée'), ('confirmee', 'Confirmée'), ('en_cours', 'En cours de séjour'), ('confirme_client', 'Confirmé par le client'), ('confirme_hotel', "Confirmé par l'hôtel"), ('terminee', 'Terminée'), ('annulee', 'Annulée'), ('remboursee', 'Remboursée')], default='en_attente', max_length=20),
        ),
    ]
