# Generated by Django 5.2.5 on 2026-06-09 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_add_politique_annulation'),
        ('reservations', '0002_add_double_confirmation_statuts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='annulation',
            name='commission_plateforme',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='annulation',
            name='frais_annulation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_ancien', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_nouveau', models.DecimalField(decimal_places=2, max_digits=12)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frais_modification', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_plateforme', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_rembourse', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('demandeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='reservations.reservation')),
                ('type_chambre_ancien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hotels.typechambre')),
                ('type_chambre_nouveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hotels.typechambre')),
            ],
            options={
                'verbose_name': 'Modification',
                'ordering': ['-date_demande'],
            },
        ),
    ]
