# Generated by Django 5.2.5 on 2026-06-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_add_modification_model_and_annulation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='modification',
            name='montant_supplementaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='modification',
            name='sens',
            field=models.CharField(choices=[('hausse', 'Hausse'), ('baisse', 'Baisse')], default='baisse', max_length=10),
        ),
    ]
