# Generated by Django 5.2.5 on 2026-06-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_modification_sens_neutre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='methode',
            field=models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('moov', 'Moov Money'), ('celtiis', 'Celtiis Money'), ('carte', 'Carte bancaire')], max_length=20),
        ),
    ]
