# Generated by Django 5.2.5 on 2026-05-09 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_marchandise', models.CharField(choices=[('alimentaire', 'Alimentaire'), ('electronique', 'Électronique'), ('textile', 'Textile'), ('construction', 'Matériaux de construction'), ('chimique', 'Produits chimiques'), ('agricole', 'Produits agricoles'), ('autre', 'Autre')], max_length=50)),
                ('description_marchandise', models.TextField(blank=True)),
                ('tonnage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ville_depart', models.CharField(choices=[('cotonou', 'Cotonou'), ('porto_novo', 'Porto-Novo'), ('parakou', 'Parakou'), ('bohicon', 'Bohicon'), ('abomey_calavi', 'Abomey-Calavi'), ('natitingou', 'Natitingou'), ('malanville', 'Malanville'), ('lome', 'Lomé (Togo)'), ('lagos', 'Lagos (Nigeria)')], max_length=50)),
                ('ville_destination', models.CharField(choices=[('cotonou', 'Cotonou'), ('porto_novo', 'Porto-Novo'), ('parakou', 'Parakou'), ('bohicon', 'Bohicon'), ('abomey_calavi', 'Abomey-Calavi'), ('natitingou', 'Natitingou'), ('malanville', 'Malanville'), ('lome', 'Lomé (Togo)'), ('lagos', 'Lagos (Nigeria)')], max_length=50)),
                ('adresse_depart', models.CharField(blank=True, max_length=255)),
                ('adresse_destination', models.CharField(blank=True, max_length=255)),
                ('date_depart_souhaitee', models.DateField()),
                ('delai_livraison', models.PositiveIntegerField(help_text='Délai en jours')),
                ('niveau_urgence', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('tres_urgent', 'Très urgent')], default='normal', max_length=20)),
                ('prix_propose', models.DecimalField(blank=True, decimal_places=2, help_text='Prix en FCFA', max_digits=12, null=True)),
                ('statut', models.CharField(choices=[('publiee', 'Publiée'), ('en_attribution', "En cours d'attribution"), ('attribuee', 'Attribuée'), ('en_transit', 'En transit'), ('livree', 'Livrée'), ('litige', 'Litige')], default='publiee', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_attribution', models.DateTimeField(blank=True, null=True)),
                ('commercant', models.ForeignKey(limit_choices_to={'role': 'commercant'}, on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to=settings.AUTH_USER_MODEL)),
                ('transporteur', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['transporteur', 'societe']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de transport',
                'verbose_name_plural': 'Demandes de transport',
                'ordering': ['-date_creation'],
            },
        ),
    ]
