# Generated by Django 5.2.5 on 2026-05-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='prix_propose',
        ),
        migrations.AlterField(
            model_name='demande',
            name='statut',
            field=models.CharField(choices=[('publiee', 'Publiée'), ('en_selection', 'En cours de sélection'), ('en_attribution', "En cours d'attribution"), ('attribuee', 'Attribuée'), ('en_transit', 'En transit'), ('livree', 'Livrée'), ('litige', 'Litige')], default='publiee', max_length=20),
        ),
    ]
