# Generated by Django 5.2.5 on 2026-05-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0002_remove_demande_prix_propose_alter_demande_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='statut',
            field=models.CharField(choices=[('publiee', 'Publiée'), ('en_negociation', 'En négociation'), ('en_selection', 'En cours de sélection'), ('en_attribution', "En cours d'attribution"), ('attribuee', 'Attribuée'), ('en_transit', 'En transit'), ('livree', 'Livrée'), ('litige', 'Litige')], default='publiee', max_length=20),
        ),
    ]
