# Generated by Django 5.2.5 on 2026-05-28 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offres', '0002_alter_offre_options_offre_date_soumission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Negociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_initial', models.DecimalField(blank=True, decimal_places=2, help_text='Copié depuis offre.prix_propose au démarrage', max_digits=12, null=True)),
                ('prix_transporteur', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('prix_commercant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('prix_final_convenu', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_cours', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('offre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='negociation', to='offres.offre')),
            ],
            options={
                'verbose_name': 'Négociation',
                'verbose_name_plural': 'Négociations',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='MessageNegociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur_type', models.CharField(choices=[('transporteur', 'Transporteur'), ('commercant', 'Commerçant')], max_length=20)),
                ('action', models.CharField(choices=[('proposition', 'Proposition de prix'), ('acceptation', 'Acceptation'), ('refus', 'Refus')], max_length=20)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('message', models.TextField(blank=True)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('negociation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='negociations.negociation')),
            ],
            options={
                'verbose_name': 'Message de négociation',
                'verbose_name_plural': 'Messages de négociation',
                'ordering': ['date_envoi'],
            },
        ),
    ]
