# Generated by Django 6.0.6 on 2026-06-06 22:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('adresse', models.CharField(max_length=300)),
                ('ville', models.CharField(max_length=100)),
                ('quartier', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site_web', models.URLField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('suspendu', 'Suspendu')], default='en_attente', max_length=20)),
                ('type_abonnement', models.CharField(choices=[('freemium', 'Freemium (3%)'), ('pro', 'Pro (1.5%)')], default='freemium', max_length=20)),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('nombre_avis', models.PositiveIntegerField(default=0)),
                ('photo_principale', models.ImageField(blank=True, null=True, upload_to='hotels/')),
                ('document_registre', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('motif_rejet', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('gestionnaire', models.ForeignKey(limit_choices_to={'role': 'gestionnaire'}, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hôtel',
                'verbose_name_plural': 'Hôtels',
                'ordering': ['-type_abonnement', '-note_moyenne'],
            },
        ),
        migrations.CreateModel(
            name='PhotoHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels/photos/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('est_principale', models.BooleanField(default=False)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Photo hôtel',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='TypeChambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('capacite', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_nuit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('prix_weekend', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('superficie', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('nombre_chambres', models.PositiveSmallIntegerField(default=1)),
                ('equipements', models.JSONField(blank=True, default=list)),
                ('est_disponible', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_chambres', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Type de chambre',
                'verbose_name_plural': 'Types de chambres',
            },
        ),
        migrations.CreateModel(
            name='PhotoChambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chambres/photos/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('type_chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='hotels.typechambre')),
            ],
            options={
                'verbose_name': 'Photo chambre',
                'ordering': ['ordre'],
            },
        ),
    ]
