# Generated by Django 5.2.5 on 2026-06-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_latitude_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
