# Generated by Django 5.2.5 on 2026-06-07 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotel_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('entrees', 'Entrées'), ('plats', 'Plats principaux'), ('grillades', 'Grillades'), ('poissons', 'Poissons & Fruits de mer'), ('vegetarien', 'Végétarien'), ('desserts', 'Desserts'), ('boissons', 'Boissons'), ('petit_dejeuner', 'Petit-déjeuner')], default='plats', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('est_disponible', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plats_menu', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Plat du menu',
                'verbose_name_plural': 'Plats du menu',
                'ordering': ['categorie', 'nom'],
            },
        ),
    ]
