# Generated by Django 5.2.5 on 2026-06-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_add_commande_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='type_abonnement',
            field=models.CharField(choices=[('freemium', 'Freemium (3%)'), ('pro', 'Pro (5%)')], default='freemium', max_length=20),
        ),
    ]
