# Generated by Django 5.2.5 on 2026-06-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_alter_hotel_type_abonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='platmenu',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='plats/'),
        ),
    ]
