# Generated by Django 5.2.5 on 2026-06-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_add_photo_to_platmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='equipements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='hotel',
            name='type_etablissement',
            field=models.CharField(choices=[('hotel', 'Hôtel'), ('residence', 'Résidence'), ('villa', 'Villa'), ('auberge', 'Auberge')], default='hotel', max_length=20),
        ),
    ]
