# Generated by Django 5.2.5 on 2026-06-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_add_type_etablissement_equipements'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='delai_gratuit',
            field=models.PositiveSmallIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='hotel',
            name='taux_annulation',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='hotel',
            name='taux_modification',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
