# Generated by Django 5.2.5 on 2026-06-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_add_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='document_identite',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
