# Generated by Django 5.2.5 on 2026-05-09 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demandes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('acceptee', 'Acceptée'), ('annulee', 'Annulée'), ('terminee', 'Terminée')], default='acceptee', max_length=20)),
                ('prix_propose', models.DecimalField(blank=True, decimal_places=2, help_text='Prix proposé par le transporteur en FCFA', max_digits=12, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('date_acceptation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offre', to='demandes.demande')),
                ('transporteur', models.ForeignKey(limit_choices_to={'role__in': ['transporteur', 'societe']}, on_delete=django.db.models.deletion.CASCADE, related_name='offres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offre',
                'verbose_name_plural': 'Offres',
                'ordering': ['-date_acceptation'],
            },
        ),
    ]
