# Generated by Django 5.2.5 on 2026-05-10 03:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0001_initial'),
        ('offres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offre',
            options={'ordering': ['-date_soumission'], 'verbose_name': 'Offre', 'verbose_name_plural': 'Offres'},
        ),
        migrations.AddField(
            model_name='offre',
            name='date_soumission',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offre',
            name='delai_propose',
            field=models.PositiveIntegerField(blank=True, help_text='Délai proposé par le transporteur en jours', null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='date_acceptation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='demandes.demande'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='message',
            field=models.TextField(blank=True, help_text='Message du transporteur au commerçant', null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('rejetee', 'Rejetée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='offre',
            name='transporteur',
            field=models.ForeignKey(limit_choices_to={'role__in': ['transporteur', 'societe']}, on_delete=django.db.models.deletion.CASCADE, related_name='offres_soumises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='offre',
            unique_together={('demande', 'transporteur')},
        ),
    ]
