# Generated by Django 6.0.6 on 2026-06-06 22:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField(blank=True)),
                ('est_approuve', models.BooleanField(default=False)),
                ('reponse_gestionnaire', models.TextField(blank=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('date_avis', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avis', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='hotels.hotel')),
                ('reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avis', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-date_avis'],
                'unique_together': {('client', 'hotel', 'reservation')},
            },
        ),
        migrations.CreateModel(
            name='SignalementAvis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('spam', 'Spam'), ('faux', 'Faux avis'), ('inapproprie', 'Contenu inapproprié'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('est_traite', models.BooleanField(default=False)),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('avis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='avis.avis')),
                ('signale_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Signalement d'avis",
            },
        ),
    ]
