# Generated by Django 5.2.5 on 2026-06-11 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0002_add_signalement_contenu'),
        ('hotels', '0010_add_promotion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalementHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('tromperie', 'Informations trompeuses'), ('hygiene', "Problème d'hygiène"), ('securite', 'Problème de sécurité'), ('escroquerie', 'Escroquerie'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('traite', 'Traité')], default='en_attente', max_length=20)),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_hotel', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_hotel', to='hotels.hotel')),
            ],
            options={
                'verbose_name': "Signalement d'hôtel",
                'ordering': ['-date_signalement'],
            },
        ),
    ]
