# Generated by Django 5.2.5 on 2026-05-10 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demandes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_chargement', 'En chargement'), ('en_transit', 'En transit'), ('livre', 'Livré'), ('litige', 'Litige')], default='en_attente', max_length=20)),
                ('confirmation', models.CharField(blank=True, choices=[('dans_les_delais', 'Dans les délais'), ('hors_delai', 'Hors délai'), ('probleme_signale', 'Problème signalé')], max_length=20, null=True)),
                ('note_confirmation', models.TextField(blank=True, help_text='Commentaire du commerçant lors de la confirmation', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_chargement', models.DateTimeField(blank=True, null=True)),
                ('date_transit', models.DateTimeField(blank=True, null=True)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('commercant', models.ForeignKey(limit_choices_to={'role': 'commercant'}, on_delete=django.db.models.deletion.CASCADE, related_name='livraisons_commercant', to=settings.AUTH_USER_MODEL)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='demandes.demande')),
                ('transporteur', models.ForeignKey(limit_choices_to={'role__in': ['transporteur', 'societe']}, on_delete=django.db.models.deletion.CASCADE, related_name='livraisons_transporteur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'ordering': ['-date_creation'],
            },
        ),
    ]
